# Generated by Django 4.2.16 on 2024-09-12 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('age', models.PositiveSmallIntegerField()),
                ('vertebled', models.BooleanField(default=True)),
                ('quadriped', models.BooleanField(default=True)),
            ],
        ),
    ]
